### ISSUE TITLE
Blinks Actions Examples: I Will Like To Add Blinks Game Development Example Code To Dialect Actions Repo

### ISSUE THREAD

**Issue by SolomonFoskaay** [dialectlabs/actions#24]
Hi Dialect Team,

Does Dialect allow contributions to the repo? 

## Why do I want to contribute to this repo?

Recently while researching to create a guide for how to build a Blinks game, I noticed there are no guides or code examples relating to Blinks game development online including the official Dialect actions example repo.

So, it took me days to figure this out because the official docs did not provide more real-world examples for action chaining in Nextjs and want to ensure other devs don't go through the same stress.

## Features Of The Blinks Game
I would like to contribute this as an example showing full blinks game development in Nextjs that includes features like:
1. The player plays the Rock Paper Scissors (RPS) game via Blinks with SOL.
2. If Loss (lose SOL amount played with)
3. If Draw (gets back exact SOL amount played with)
4. If Win (gets back double the SOL amount played with)
5. ***Win/Draw SOL rewards are sent to the player instantly using action chaining (Post method in Nextjs)*** 
6. All Player moves and results (wins/losses) are recorded on-chain (using Memo)

I just published the guide here - [Solana Blinks Development Ep2: Ultimate Guide To Build Blinks Games (Rock Paper Scissors (RPS) Game Blinks)](https://dprogramminguniversity.com/solana-blinks-guides/ep2-ultimate-guide-to-build-blinks-games-rps-game-blinks/)

Aside from the guide I want to contribute the source code as a real-world working example of Nextjs code in Dialect official repo if permitted.

Thanks!

**Comment by zhelezkov** [comment]
hey, absolutely, feel free to submit a PR
